# Generated by Django 3.1.7 on 2021-10-07 18:15

from django.db import migrations, models
import shapeeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=80)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('history_json', models.JSONField(editable=False)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('shape_id', models.CharField(db_index=True, max_length=80, primary_key=True, serialize=False)),
                ('lines', models.JSONField(default=shapeeditor.models.default_shape_line)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(db_index=True, max_length=80, primary_key=True, serialize=False)),
                ('lines', models.JSONField(default=shapeeditor.models.default_stop_line)),
            ],
        ),
    ]
